### ISSUE TITLE
ProviderError: Error: Transaction reverted: function selector was not recognized and there's no fallback function

### ISSUE THREAD

**Issue by ghost** [PatrickAlphaC/hardhat-dao-fcc#1]
In the file propose.ts, I've been trying to call the governor.propose, like this...

```
const governor = await ethers.getContract("GovernorContract");
const box = await ethers.getContract("Box");

    //because in the propose function, it takes bytes calldata that what function to call in bytes. 
    const encodedFunctionCall = box.interface.encodeFunctionData(functionToCall, args);
```

same as in the video guide. After getting the contract's address... I'm doing

```
const proposeTx = await governor.propose(
        [box.address],
        [0],
        [encodedFunctionCall],
        proposalDescription
    );
```

But [encodedFunctionCall] is creating error...

```
Error: Transaction reverted: function selector was not recognized and there's no fallback function
      at Box.<unrecognized-selector> (contracts/Box.sol:6)
      at GovernorContract.getVotes (@openzeppelin/contracts/governance/extensions/GovernorVotes.sol:25)
      at GovernorContract.getVotes (contracts/Governance_Standard/GovernorContract.sol:62)
      at GovernorContract.propose (@openzeppelin/contracts/governance/Governor.sol:200)
      at GovernorContract.propose (contracts/Governance_Standard/GovernorContract.sol:80)
      at async EthModule._estimateGasAction (/home/adil/Desktop/MakingDAO/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:425:7)
      at async HardhatNetworkProvider._sendWithLogging (/home/adil/Desktop/MakingDAO/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:139:22)
      at async HardhatNetworkProvider.request (/home/adil/Desktop/MakingDAO/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:116:18)
      at async JsonRpcHandler._handleRequest (/home/adil/Desktop/MakingDAO/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
      at async JsonRpcHandler._handleSingleRequest (/home/adil/Desktop/MakingDAO/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:167:17)
      at async Server.JsonRpcHandler.handleHttp (/home/adil/Desktop/MakingDAO/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:52:21)
```

I don't know why my function selector is not being recognized, I'm also consoling the selector, and getting this...

`0x6057361d000000000000000000000000000000000000000000000000000000000000004d`

My whole question that is still unanswered is posted on [here](https://ethereum.stackexchange.com/questions/124235/providererror-error-transaction-reverted-function-selector-was-not-recognized). 

Thanks in advance.

**Comment by PatrickAlphaC** [comment]
I think you're looking for https://github.com/PatrickAlphaC/dao-template ?

This repo hasn't been released yet!
